#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
    exit("Usage {0} TEMPLATE_FILE".format(sys.argv[0]))

from libfritter.email_template import EmailTemplate
from libfritter.previewer import Previewer
from libfritter.template_source import load_path

content = load_path(sys.argv[1])
et = EmailTemplate(content)

p = Previewer(et)

p.preview(sys.stdout)
