#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
    exit("Usage {0} TEMPLATE_FILE".format(sys.argv[0]))

from libfritter.email_template import EmailTemplate
from libfritter.previewer import Previewer
from libfritter.template_source import load_path

def load(path):
    return EmailTemplate(load_path(path))

p = Previewer(load, sys.stdout)
p.preview(sys.argv[1])
